server:
  port: 8090


spring:
  application:
    name: loans
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
     - "qa"
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb
#    driverClassName: org.h2.Driver
    username: root
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
  
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

 
build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
   
info:
  app:
    name: "loans"
    description: "Loans Application"
    version: "1.0.0"